server:
  port: 8082
spring:
    datasource:
        name: template
        url: jdbc:mysql://127.0.0.1:3306/Template
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #根据url自动识别
        #这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
        driver-class-name: com.mysql.jdbc.Driver
        #属性类型是字符串，通过别名的方式配置扩展插件，
         #常用的插件有：
         #监控统计用的filter:stat
         #日志用的filter:log4j
        #防御sql注入的filter:wall
        filters: stat
        #最大连接池数量
        maxActive: 20
        #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        initialSize: 1
        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，
        #缺省启用公平锁，并发效率会有所下降，
        #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        maxWait: 60000
        #有两个含义：
        #1) Destroy线程会检测连接的间隔时间
        #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        #用来检测连接是否有效的sql，要求是一个查询语句。
        #如果validationQuery为null，testOnBorrow、testOnReturn、
        #testWhileIdle都不会其作用。
        validationQuery: select 'x'
        #建议配置为true，不影响性能，并且保证安全性。
        # 申请连接的时候检测，如果空闲时间大于
        # timeBetweenEvictionRunsMillis，
         #执行validationQuery检测连接是否有效。
        testWhileIdle: true
        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false
        #是否缓存preparedStatement，也就是PSCache。
        #PSCache对支持游标的数据库性能提升巨大，比如说oracle。
        #在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
        #作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
        #该应该是支持PSCache。
        poolPreparedStatements: true
        #要启用PSCache，必须配置大于0，当大于0时，
        #poolPreparedStatements自动触发修改为true。
        #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
        #可以把这个数值配置大一些，比如说100
        maxOpenPreparedStatements: 20
    # 属性其实都在这个类里 org.springframework.boot.autoconfigure.thymeleaf.ThymeleafProperties
    thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      #开发时关闭缓存,不然没法看到实时页面  ctrl+f9重新编译
      cache: false
      prefix: classpath:/templates/
      suffix: .html
    #国际化需要配置这里
    messages:
      basename: i18n/login
#    profiles: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lyp.tempalte.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
      com:
       template:
        mapper: DEBUG